name: Android CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Remove or do not set org.gradle.java.home in gradle.properties, or:
      - name: Remove org.gradle.java.home from gradle.properties if present
        run: sed -i '/org.gradle.java.home/d' gradle.properties
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle (Debug)
        run: ./gradlew build --stacktrace --info
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
            name: schoolspace-app
            path: app/build/outputs/apk/debug/*.apk

